name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Install linters
        run: |
          go install golang.org/x/tools/cmd/goimports@latest
      - name: Check formatting
        run: |
          gofmt -l .
      - name: Run vet
        run: go vet ./...
      - name: Run tests
        run: go test ./...
